name: CI/CD on Self-Hosted Runner

on:
  push:
    branches: [ "main" ] # Chạy khi push code vào main

jobs:
  deploy:
    # QUAN TRỌNG: Dùng runner của chính bạn thay vì ubuntu-latest
    runs-on: ["self-hosted", "server-runner-arkive"]

    steps:
      # 1. Check out code mới nhất từ GitHub về thư mục làm việc của Runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- BƯỚC QUAN TRỌNG: COPY FILE CÓ SẴN VÀO WORKSPACE ---
      - name: Copy existing .env from Server
        run: |
          
          echo "Đang copy file cấu hình..."
          cp ~/Arkive/ArkiveBackEnd/.env ./ArkiveBackEnd/.env
          
          # Kiểm tra xem file đã đến nơi chưa
          ls -la ./ArkiveBackEnd/

          cp ~/Arkive/ArkiveFrontEnd/.env ./ArkiveFrontEnd/.env
          ls -la ./ArkiveFrontEnd/

      # 2. Build và Chạy Docker Compose
      - name: Build and Deploy
        run: |
          echo "Building and Starting Containers..."
          # Dùng 'docker compose' (bản mới) thay vì 'docker-compose' (bản cũ)
          docker compose down
          docker compose up -d --build

      # 3. Dọn dẹp image cũ cho đỡ tốn ổ cứng
      - name: Cleanup
        run: docker system prune -f